# providers = ['node']
# buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1741046653'

# [variables]
# CI = 'true'
# NIXPACKS_METADATA = 'node'
# NODE_ENV = 'production'
# NPM_CONFIG_PRODUCTION = 'false'
# [phases.build]
# dependsOn = ['install']
# cmds = ['bun --bun run build']
# cacheDirectories = ['node_modules/.cache']

# [phases.install]
# dependsOn = ['setup']
# cmds = ['bun i']
# cacheDirectories = ['/root/.bun']
# paths = ['/app/node_modules/.bin']

# [phases.setup]
# nixPkgs = ['nodejs_18', 'openssl', 'curl', 'unzip']
# cmds = [
#     'curl -fsSL https://bun.sh/install | bash',
#     'source /root/.bashrc',
#     'bun --help',
# ]
# nixOverlays = [
#     'https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz',
# ]
# nixpkgsArchive = 'ffeebf0acf3ae8b29f8c7049cd911b9636efd7e7'

providers = ['node']
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1741046653'

[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'
[phases.build]
dependsOn = ['install']
cmds = ['bun --bun run build']
cacheDirectories = ['node_modules/.cache']

[phases.install]
dependsOn = ['setup']
cmds = ['bun i']
cacheDirectories = ['/root/.bun']
paths = ['/app/node_modules/.bin']

[phases.setup]
# cmds = [
#     'curl -fsSL https://bun.sh/install | bash',
#     'source /root/.bashrc',
#     'bun --help',
# ]
nixPkgs = ['nodejs_18', 'bun', 'openssl', 'unzip']

[start]
cmd = "bun --bun ./dist/server/entry.mjs"
